cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'iterm2'
cask 'atom'
cask 'evernote'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'tunnelbear'
cask 'dash'
cask 'spotify'
