# docker images
# docker tag 844814bd216f shanshanyang/docker-whale:latest
# docker login --username=shanshanyang --email=shanshanyang.ny@gmail.com
# docker push shanshanyang/docker-whale
# docker rmi -f 844814bd216f
# docker run shanshanyang/docker-whale
# docker build -t web .
# docker-compose up
# docker-compose up --build

## Get IP addresses of Docker host on MAC: 71.172.162.182
# docker-machine ip [MACHINE_VM]

## Docker Machine: ~/.docker/machine/machines/default
# docker-machine ls
# docker-machine rm <machine-name>
# docker-machine create -d virtualbox --virtualbox-import-boot2docker-vm boot2docker-vm docker-vm

## Mac docker installation steps
## Display Running Docker Container
# docker ps
## Access container ports
# docker run -d -P --name web nginx
## web container’s port 80 is mapped to port 32769 on your Docker host
# docker port web
## set DOCKER_HOST address to localhost address
# docker-machine ip default

## stop and remove running docker container
# docker stop <web>
# docker rm <web>


## Mount a volume on the container
# docker run -d -P -v <$HOME/AWS>:/usr/share/nginx/html --name mysite nginx

## Docker Engine, Docker Compose


## Delete Docker toolbox
## Remove docker machines from Directory ~/.docker/machine/machines
# docker-machine rm <dev>

## Remove docker, docker-compose, docker-machine command from /usr/local/bin
# rm /usr/local/bin/docker
# rm -rf ~/.docker
